travis:
  secure:
    BINSTAR_TOKEN: O0XQ23JiZHMkzd9Gy2kZ/3hJLd8D/2TTX8K2W5Uz5B9OmLRGwj9mLHi/j7zaJEHVRsqTeOYY2OydurmeKAfNj/PO1BESJwDweqFNWRiLfj5EjlYWNl9YVEbmklGG/2AZB06h5d7NBUjERHenrJZF1upY9mWcRyYZdwuvOM1rdwGCSqCDjWHWUbGyOTWh+SAj6Cjugn8hPbhk5IyNwNTdisPaUJSSFC9t/ZfbpOh2/jxhv/LfIbbwOaEnyx//gG5oSwpHY4t13KXBpp5S19y/wIElf85cPqV8bIJNiLTwIyuUdrBBNchpevabc22P4eaIKEsvFJHTmdSxcpRqdYQjAgigaeLgYj0/4DRLyXPWkek/QBS2OqKwnuf1q9GCgIoj0NwYOCBd9TnjC5mK9HReZ5euQfbIDRO1srvgBZHFQ/j4O+JEedcPwBRkHjb0upgwO2veDjpWzq2s7lc+0tBrmKB1w1cO3CFU2+TT71pg2r1NdNZP9KlIWpQkP5MqXc4Kbc4GTwgW+6oE19IYN/qeLpeir2mfeCwBpD+8lo/pfVZHNJGg6rxrGCznFPoYCMsWhWhN685V9mYfOCJEhFesEWXKyvZCGODpsc8Uuwt7liFnefxwEM02HGYDzb+fnUmajyxB9wmABIZkGND5x+IpVg1KCdiu9FP/C9WtG9ihD8U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
